set nocompatible              " be iMproved, required 
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'tpope/vim-fugitive'
Plugin 'https://github.com/itchyny/lightline.vim'
Plugin 'https://github.com/tpope/vim-surround'
Plugin 'https://github.com/skammer/vim-css-color'
Plugin 'https://github.com/Shutnik/jshint2.vim'
"Plugin 'git://git.wincent.com/command-t.git'
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'mattn/emmet-vim'
"Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'scrooloose/nerdtree'
call vundle#end()            " required
filetype plugin indent on    " required
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set nu
colorscheme default
set backspace=indent,eol,start
syntax enable

" Custom key mapping of hm
nmap nerd :NERDTree<CR>
nmap <F9> :NERDTreeToggle<CR>
"nmap <C-b><Up>		<C-w>k
"nmap <C-b><Down>	<C-w>j
"nmap <C-b><Left>	<C-w>h 
"nmap <C-b><Right>	<C-w>l
